In [1]:
import yfinance as yf
from datetime import  datetime
import pandas as pd

In [2]:
symbol = input("Symbol = ")
start_date = input(f"Start date = (YYYY-MM-DD)").strip()
end_date = input(f"End date = (YYYY-MM-DD)").strip()
interval = input("interval = (1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo)")  
mapping_symbol = {
    "0P0000HY8X.VN": "VNINDEX",
    "KO": "coca.cola",
    "BTC-USD": "btc",
    "ETH-USD": "eth",
    "AAPL": "apple"
}
stock = yf.Ticker(symbol)

In [3]:
stock.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 164000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 62,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'totalPay': 16239562,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Luca  Maestri',
   'age': 60,
   'title': 'CFO & Senior VP',
   'yearBorn': 1963,
   'fiscalYear': 2023,
   'totalPay': 4612242,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 59,
   'title': 'Chief Operating Officer',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4637585,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 59,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4618064,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 56,
   'title': 'Chief People Officer & Senior VP of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 4613369,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 49,
   'title': 'Head of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Michael  Fenger',
   'title': 'VP of Worldwide Sales',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 1,
 'compensationRisk': 2,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1732752000,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://investor.apple.com/',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 234.93,
 'open': 234.84,
 'dayLow': 233.97,
 'dayHigh': 237.81,
 'regularMarketPreviousClose': 234.93,
 'regularMarketOpen': 234.84,
 'regularMarketDayLow': 233.97,
 'regularMarketDayHigh': 237.81,
 'dividendRate': 1.0,
 'dividendYield': 0.0042,
 'exDividendDate': 1731024000,
 'payoutRatio': 0.1612,
 'fiveYearAvgDividendYield': 0.62,
 'beta': 1.24,
 'trailingPE': 39.034542,
 'forwardPE': 28.568161,
 'volume': 28220021,
 'regularMarketVolume': 28220021,
 'averageVolume': 48484395,
 'averageVolume10days': 44238650,
 'averageDailyVolume10Day': 44238650,
 'bid': 237.33,
 'ask': 237.68,
 'bidSize': 300,
 'askSize': 500,
 'marketCap': 3587432775680,
 'fiftyTwoWeekLow': 164.08,
 'fiftyTwoWeekHigh': 237.81,
 'priceToSalesTrailing12Months': 9.174199,
 'fiftyDayAverage': 228.8844,
 'twoHundredDayAverage': 205.82645,
 'trailingAnnualDividendRate': 0.98,
 'trailingAnnualDividendYield': 0.0041714557,
 'currency': 'USD',
 'enterpriseValue': 3641326174208,
 'profitMargins': 0.23971,
 'floatShares': 15091184209,
 'sharesOutstanding': 15115799552,
 'sharesShort': 141037864,
 'sharesShortPriorMonth': 140919653,
 'sharesShortPreviousMonthDate': 1728950400,
 'dateShortInterest': 1731628800,
 'sharesPercentSharesOut': 0.0093,
 'heldPercentInsiders': 0.02056,
 'heldPercentInstitutions': 0.61919,
 'shortRatio': 3.21,
 'shortPercentOfFloat': 0.0093,
 'impliedSharesOutstanding': 15332100096,
 'bookValue': 3.767,
 'priceToBook': 63.00239,
 'lastFiscalYearEnd': 1727481600,
 'nextFiscalYearEnd': 1759017600,
 'mostRecentQuarter': 1727481600,
 'earningsQuarterlyGrowth': -0.358,
 'netIncomeToCommon': 93736001536,
 'trailingEps': 6.08,
 'forwardEps': 8.31,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.312,
 'enterpriseToEbitda': 27.041,
 '52WeekChange': 0.25286388,
 'SandP52WeekChange': 0.32005918,
 'lastDividendValue': 0.25,
 'lastDividendDate': 1731024000,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'AAPL',
 'underlyingSymbol': 'AAPL',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'firstTradeDateEpochUtc': 345479400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': '8b10e4ae-9eeb-3684-921a-9ab27e4d87aa',
 'messageBoardId': 'finmb_24937',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 237.33,
 'targetHighPrice': 300.0,
 'targetLowPrice': 184.0,
 'targetMeanPrice': 244.47739,
 'targetMedianPrice': 250.0,
 'recommendationMean': 1.89362,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 42,
 'totalCash': 65171001344,
 'totalCashPerShare': 4.311,
 'ebitda': 134660997120,
 'totalDebt': 119058997248,
 'quickRatio': 0.745,
 'currentRatio': 0.867,
 'totalRevenue': 391034994688,
 'debtToEquity': 209.059,
 'revenuePerShare': 25.485,
 'returnOnAssets': 0.21464,
 'returnOnEquity': 1.5741299,
 'freeCashflow': 110846001152,
 'operatingCashflow': 118254002176,
 'earningsGrowth': -0.341,
 'revenueGrowth': 0.061,
 'grossMargins': 0.46206,
 'ebitdaMargins': 0.34437,
 'operatingMargins': 0.31171,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.4521}

In [4]:
hist = stock.history()

In [5]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-10-30 00:00:00-04:00,232.354358,233.213414,229.297724,229.847122,47070900,0.00,0.0
2024-10-31 00:00:00-04:00,229.087951,229.577418,225.122313,225.661728,64370100,0.00,0.0
2024-11-01 00:00:00-04:00,220.727153,225.102345,220.027926,222.665024,65276700,0.00,0.0
2024-11-04 00:00:00-05:00,220.747138,222.545148,219.468546,221.766006,44944500,0.00,0.0
2024-11-05 00:00:00-05:00,221.556241,223.703872,220.896963,223.204422,28111300,0.00,0.0
2024-11-06 00:00:00-05:00,222.365355,225.821559,220.946918,222.475235,54561100,0.00,0.0
2024-11-07 00:00:00-05:00,224.383137,227.629565,224.323205,227.229996,42137700,0.00,0.0
2024-11-08 00:00:00-05:00,227.169998,228.660004,226.410004,226.960007,38328800,0.25,0.0
2024-11-11 00:00:00-05:00,225.000000,225.699997,221.500000,224.229996,42005600,0.00,0.0
2024-11-12 00:00:00-05:00,224.550003,225.589996,223.360001,224.229996,40398300,0.00,0.0
2024-11-13 00:00:00-05:00,224.009995,226.649994,222.759995,225.119995,48566200,0.00,0.0
2024-11-14 00:00:00-05:00,225.020004,228.869995,225.000000,228.220001,44923900,0.00,0.0
2024-11-15 00:00:00-05:00,226.399994,226.919998,224.270004,225.000000,47923700,0.00,0.0
2024-11-18 00:00:00-05:00,225.250000,229.740005,225.169998,228.020004,44686000,0.00,0.0
2024-11-19 00:00:00-05:00,226.979996,230.160004,226.660004,228.279999,36211800,0.00,0.0
2024-11-20 00:00:00-05:00,228.059998,229.929993,225.889999,229.000000,35169600,0.00,0.0
2024-11-21 00:00:00-05:00,228.880005,230.160004,225.710007,228.520004,42108300,0.00,0.0
2024-11-22 00:00:00-05:00,228.059998,230.720001,228.059998,229.869995,38168300,0.00,0.0
2024-11-25 00:00:00-05:00,231.460007,233.250000,229.740005,232.869995,90152800,0.00,0.0
2024-11-26 00:00:00-05:00,233.330002,235.570007,233.330002,235.059998,45986200,0.00,0.0
2024-11-27 00:00:00-05:00,234.470001,235.690002,233.809998,234.929993,33498400,0.00,0.0
2024-11-29 00:00:00-05:00,234.809998,237.809998,233.970001,237.330002,28481400,0.00,0.0

In [6]:
hist = stock.history(
    start=start_date,
    interval=interval,
    end=end_date
)

In [7]:
str(hist.index.min().date())

'2002-01-02'

In [8]:
str(hist.index.max().date())

'2024-11-29'

In [9]:
hist.index = hist.index.strftime('%Y-%m-%d %H:%M:%S')
hist.index = pd.to_datetime(hist.index).tz_localize('UTC')

In [10]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-01-02 00:00:00+00:00,0.332147,0.350975,0.330791,0.350975,529496800,0.0,0.0
2002-01-03 00:00:00+00:00,0.346457,0.357754,0.342992,0.355193,612007200,0.0,0.0
2002-01-04 00:00:00+00:00,0.351579,0.360767,0.346306,0.356851,409976000,0.0,0.0
2002-01-07 00:00:00+00:00,0.357302,0.361520,0.342691,0.344951,444584000,0.0,0.0
2002-01-08 00:00:00+00:00,0.342691,0.347210,0.338322,0.340582,450038400,0.0,0.0
...,...,...,...,...,...,...,...
2024-11-22 00:00:00+00:00,228.059998,230.720001,228.059998,229.869995,38168300,0.0,0.0
2024-11-25 00:00:00+00:00,231.460007,233.250000,229.740005,232.869995,90152800,0.0,0.0
2024-11-26 00:00:00+00:00,233.330002,235.570007,233.330002,235.059998,45986200,0.0,0.0
2024-11-27 00:00:00+00:00,234.470001,235.690002,233.809998,234.929993,33498400,0.0,0.0
2024-11-29 00:00:00+00:00,234.809998,237.809998,233.970001,237.330002,28481400,0.0,0.0

In [11]:
symbol =  mapping_symbol.get(symbol, symbol)

In [12]:
symbol = symbol.replace(".", "_").lower()

In [13]:
file_name = f"../../data/{symbol}/{symbol}_to_now_{interval.lower()}.csv"

In [14]:
file_name = file_name.replace("-", "_")

In [15]:
file_name

'../../data/apple/apple_to_now_1d.csv'

In [17]:

hist.to_csv(file_name)