In [34]:
import yfinance as yf
from datetime import  datetime
import pandas as pd

In [35]:
symbol = input("Symbol = ")
start_date = input(f"Start date = (YYYY-MM-DD)").strip()
end_date = input(f"End date = (YYYY-MM-DD)").strip()
interval = input("interval = (1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo)")  
mapping_symbol = {
    "0P0000HY8X.VN": "VNINDEX",
    "KO": "coca.cola",
    "BTC-USD": "btc",
    "ETH-USD": "eth"
}
stock = yf.Ticker(symbol)

In [36]:
stock.info

{'twitter': '"https://twitter.com/ethereum"',
 'name': 'Ethereum',
 'startDate': 1438905600,
 'description': 'Ethereum (ETH) is a cryptocurrency . Ethereum has a current supply of 120,441,030.04711388. The last known price of Ethereum is 3,703.74257296 USD and is up 0.42 over the last 24 hours. It is currently trading on 9614 active market(s) with $27,178,075,231.37 traded over the last 24 hours. More information can be found at https://www.ethereum.org/.',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 3705.9707,
 'open': 3705.9707,
 'dayLow': 3665.8455,
 'dayHigh': 3729.033,
 'regularMarketPreviousClose': 3705.9707,
 'regularMarketOpen': 3705.9707,
 'regularMarketDayLow': 3665.8455,
 'regularMarketDayHigh': 3729.033,
 'volume': 26355824640,
 'regularMarketVolume': 26355824640,
 'averageVolume': 21746214267,
 'averageVolume10days': 38061938619,
 'averageDailyVolume10Day': 38061938619,
 'marketCap': 444856991744,
 'fiftyTwoWeekLow': 2113.9253,
 'fiftyTwoWeekHigh': 4092.2842,
 'fiftyDayAverage': 2900.94,
 'twoHundredDayAverage': 2981.9524,
 'currency': 'USD',
 'fromCurrency': 'ETH',
 'toCurrency': 'USD=X',
 'lastMarket': 'CoinMarketCap',
 'coinMarketCapLink': 'https://coinmarketcap.com/currencies/ethereum',
 'volume24Hr': 26355824640,
 'volumeAllCurrencies': 26355824640,
 'circulatingSupply': 120441032,
 'exchange': 'CCC',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'ETH-USD',
 'underlyingSymbol': 'ETH-USD',
 'shortName': 'Ethereum USD',
 'longName': 'Ethereum USD',
 'firstTradeDateEpochUtc': 1510185600,
 'timeZoneFullName': 'UTC',
 'timeZoneShortName': 'UTC',
 'uuid': 'c32b80a9-b35b-3c25-9500-7c2b54dfcc04',
 'messageBoardId': 'finmb_ETH_CCC',
 'trailingPegRatio': None}

In [37]:
hist = stock.history()

In [38]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-11-01 00:00:00+00:00,2515.870361,2583.777100,2467.819336,2511.885498,20215438328,0.0,0.0
2024-11-02 00:00:00+00:00,2512.208252,2522.360596,2471.955566,2491.068604,9639457439,0.0,0.0
2024-11-03 00:00:00+00:00,2491.094482,2495.436523,2411.398438,2456.425293,15667779706,0.0,0.0
2024-11-04 00:00:00+00:00,2456.095215,2488.350342,2359.578125,2397.026367,17110200696,0.0,0.0
2024-11-05 00:00:00+00:00,2397.036377,2478.618896,2380.601318,2422.650635,17894057485,0.0,0.0
2024-11-06 00:00:00+00:00,2422.539307,2743.964111,2421.812988,2724.169189,41887574364,0.0,0.0
2024-11-07 00:00:00+00:00,2724.005859,2918.744385,2701.590820,2895.585449,35352318438,0.0,0.0
2024-11-08 00:00:00+00:00,2895.597900,2983.744873,2889.484375,2962.296631,32303261101,0.0,0.0
2024-11-09 00:00:00+00:00,2962.791016,3156.366211,2957.182373,3131.144531,29210133088,0.0,0.0
2024-11-10 00:00:00+00:00,3130.729248,3249.914062,3073.248779,3191.331299,47418730187,0.0,0.0
2024-11-11 00:00:00+00:00,3191.656982,3389.529297,3109.769531,3374.812988,55417771668,0.0,0.0
2024-11-12 00:00:00+00:00,3375.154785,3444.154053,3211.198486,3246.257324,56686078066,0.0,0.0
2024-11-13 00:00:00+00:00,3244.543213,3337.877197,3121.666016,3192.595947,52010205682,0.0,0.0
2024-11-14 00:00:00+00:00,3192.520508,3240.270752,3032.971924,3058.948730,35743352141,0.0,0.0
2024-11-15 00:00:00+00:00,3059.526123,3130.703857,3016.144043,3103.040527,32701369872,0.0,0.0
2024-11-16 00:00:00+00:00,3089.739990,3218.089600,3073.286377,3133.273926,26650658846,0.0,0.0
2024-11-17 00:00:00+00:00,3133.306641,3160.152588,3039.246826,3075.661621,28348163224,0.0,0.0
2024-11-18 00:00:00+00:00,3075.722900,3225.130615,3052.491211,3207.856445,35445557613,0.0,0.0
2024-11-19 00:00:00+00:00,3208.250488,3222.004395,3070.362793,3111.384033,29823634432,0.0,0.0
2024-11-20 00:00:00+00:00,3111.116943,3159.949463,3032.603271,3072.187988,29785491216,0.0,0.0
2024-11-21 00:00:00+00:00,3072.055176,3388.542969,3035.846680,3361.053955,51619069348,0.0,0.0
2024-11-22 00:00:00+00:00,3360.654297,3428.460449,3262.808838,3331.600830,36775716442,0.0,0.0
2024-11-23 00:00:00+00:00,3331.645508,3499.370850,3317.654785,3396.223389,38835184688,0.0,0.0
2024-11-24 00:00:00+00:00,3396.999512,3451.802246,3288.430908,3363.659912,27901454185,0.0,0.0
2024-11-25 00:00:00+00:00,3364.601562,3545.278809,3304.093994,3413.543945,51544793988,0.0,0.0
2024-11-26 00:00:00+00:00,3412.950928,3461.292969,3255.542969,3326.517334,39902959158,0.0,0.0
2024-11-27 00:00:00+00:00,3326.029053,3687.009033,3303.567871,3657.249268,43383987191,0.0,0.0
2024-11-28 00:00:00+00:00,3656.609619,3664.878174,3531.870605,3579.811523,32362724276,0.0,0.0
2024-11-29 00:00:00+00:00,3579.910645,3647.264404,3538.446777,3593.494385,27622629486,0.0,0.0
2024-11-30 00:00:00+00:00,3593.598145,3739.934814,3572.254150,3705.705322,30670867436,0.0,0.0
2024-12-01 00:00:00+00:00,3705.970703,3729.032959,3665.845459,3693.566650,26355824640,0.0,0.0

In [39]:
hist = stock.history(
    start=start_date,
    interval=interval,
    end=end_date
)

In [40]:
str(hist.index.min().date())

'2017-11-09'

In [41]:
str(hist.index.max().date())

'2024-11-30'

In [42]:
hist.index = hist.index.strftime('%Y-%m-%d %H:%M:%S')
hist.index = pd.to_datetime(hist.index).tz_localize('UTC')

In [43]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2017-11-09 00:00:00+00:00,308.644989,329.451996,307.056000,320.884003,893249984,0.0,0.0
2017-11-10 00:00:00+00:00,320.670990,324.717987,294.541992,299.252991,885985984,0.0,0.0
2017-11-11 00:00:00+00:00,298.585999,319.453003,298.191986,314.681000,842300992,0.0,0.0
2017-11-12 00:00:00+00:00,314.690002,319.153015,298.513000,307.907990,1613479936,0.0,0.0
2017-11-13 00:00:00+00:00,307.024994,328.415009,307.024994,316.716003,1041889984,0.0,0.0
...,...,...,...,...,...,...,...
2024-11-26 00:00:00+00:00,3412.950928,3461.292969,3255.542969,3326.517334,39902959158,0.0,0.0
2024-11-27 00:00:00+00:00,3326.029053,3687.009033,3303.567871,3657.249268,43383987191,0.0,0.0
2024-11-28 00:00:00+00:00,3656.609619,3664.878174,3531.870605,3579.811523,32362724276,0.0,0.0
2024-11-29 00:00:00+00:00,3579.910645,3647.264404,3538.446777,3593.494385,27622629486,0.0,0.0
2024-11-30 00:00:00+00:00,3593.598145,3739.934814,3572.254150,3705.705322,30670867436,0.0,0.0

In [44]:
symbol =  mapping_symbol.get(symbol, symbol)

In [45]:
symbol = symbol.replace(".", "_").lower()

In [46]:
file_name = f"../../data/{symbol}/{symbol}_to_now_{interval.lower()}.csv"

In [47]:
file_name = file_name.replace("-", "_")

In [48]:
file_name

'../../data/eth/eth_to_now_1d.csv'

In [49]:

hist.to_csv(file_name)