In [1]:
import yfinance as yf
from datetime import  datetime
import pandas as pd

In [2]:
symbol = "KO"
start_date = "1980-01-01"
interval = "1wk"
mapping_symbol = {
    "0P0000HY8X.VN": "VNINDEX",
    "KO": "coca.cola"
}
stock = yf.Ticker(symbol)

In [3]:
stock.info

{'address1': 'One Coca-Cola Plaza',
 'city': 'Atlanta',
 'state': 'GA',
 'zip': '30313',
 'country': 'United States',
 'phone': '404 676 2121',
 'website': 'https://www.coca-colacompany.com',
 'industry': 'Beverages - Non-Alcoholic',
 'industryKey': 'beverages-non-alcoholic',
 'industryDisp': 'Beverages - Non - Alcoholic',
 'sector': 'Consumer Defensive',
 'sectorKey': 'consumer-defensive',
 'sectorDisp': 'Consumer Defensive',
 'longBusinessSummary': 'The Coca-Cola Company, a beverage company, manufactures, markets, and sells various nonalcoholic beverages worldwide. The company provides sparkling soft drinks, sparkling flavors; water, sports, coffee, and tea; juice, value-added dairy, and plant-based beverages; and other beverages. It also offers beverage concentrates and syrups, as well as fountain syrups to fountain retailers, such as restaurants and convenience stores. The company sells its products under the Coca-Cola, Diet Coke/Coca-Cola Light, Coca-Cola Zero Sugar, caffeine free Diet Coke, Cherry Coke, Fanta Orange, Fanta Zero Orange, Fanta Zero Sugar, Fanta Apple, Sprite, Sprite Zero Sugar, Simply Orange, Simply Apple, Simply Grapefruit, Fresca, Schweppes, Thums Up, Aquarius, Ayataka, BODYARMOR, Ciel, Costa, Dasani, dogadan, FUZE TEA, Georgia, glacéau smartwater, glacéau vitaminwater, Gold Peak, Ice Dew, I LOHAS, Powerade, Topo Chico, AdeS, Del Valle, fairlife, innocent, Minute Maid, and Minute Maid Pulpy brands. It operates through a network of independent bottling partners, distributors, wholesalers, and retailers, as well as through bottling and distribution operators. The company was founded in 1886 and is headquartered in Atlanta, Georgia.',
 'fullTimeEmployees': 79100,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. James Robert B. Quincey',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1965,
   'fiscalYear': 2023,
   'totalPay': 8305056,
   'exercisedValue': 8093571,
   'unexercisedValue': 28561432},
  {'maxAge': 1,
   'name': 'Mr. John  Murphy',
   'age': 61,
   'title': 'President & CFO',
   'yearBorn': 1962,
   'fiscalYear': 2023,
   'totalPay': 4366140,
   'exercisedValue': 3890558,
   'unexercisedValue': 8965029},
  {'maxAge': 1,
   'name': 'Mr. Manuel Arroyo Prieto',
   'age': 56,
   'title': 'Executive VP & Global chief Marketing Officer',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 2930594,
   'exercisedValue': 0,
   'unexercisedValue': 3166390},
  {'maxAge': 1,
   'name': 'Mr. Henrique  Braun',
   'age': 55,
   'title': 'Executive VP & President of International Development',
   'yearBorn': 1968,
   'fiscalYear': 2023,
   'totalPay': 3608946,
   'exercisedValue': 1041552,
   'unexercisedValue': 4121619},
  {'maxAge': 1,
   'name': 'Ms. Jennifer Kay Mann',
   'age': 51,
   'title': 'Executive VP & President of North America Operating Unit',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 2094554,
   'exercisedValue': 0,
   'unexercisedValue': 3378083},
  {'maxAge': 1,
   'name': 'Ms. Erin  May',
   'age': 44,
   'title': 'Senior VP, Chief Accounting Officer & Controller',
   'yearBorn': 1979,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Stacy Lynn  Apter',
   'age': 57,
   'title': 'Senior VP, Treasurer & Head of Corporate Finance',
   'yearBorn': 1966,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Nancy W. Quan',
   'age': 57,
   'title': 'Executive VP and Global Chief Technical & Innovation Officer',
   'yearBorn': 1966,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Neeraj  Tolmare',
   'age': 49,
   'title': 'Senior VP & Chief Information Officer',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Robin  Halpern',
   'title': 'VP & Head of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 7,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 4,
 'overallRisk': 2,
 'governanceEpochDate': 1730419200,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://www.coca-colacompany.com/investors/',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 62.99,
 'open': 63.15,
 'dayLow': 62.95,
 'dayHigh': 63.81,
 'regularMarketPreviousClose': 62.99,
 'regularMarketOpen': 63.15,
 'regularMarketDayLow': 62.95,
 'regularMarketDayHigh': 63.81,
 'dividendRate': 1.94,
 'dividendYield': 0.0304,
 'exDividendDate': 1732838400,
 'payoutRatio': 0.7946,
 'fiveYearAvgDividendYield': 3.02,
 'beta': 0.62,
 'trailingPE': 26.45643,
 'forwardPE': 21.264957,
 'volume': 17073342,
 'regularMarketVolume': 17073342,
 'averageVolume': 14486746,
 'averageVolume10days': 16518910,
 'averageDailyVolume10Day': 16518910,
 'bidSize': 3200,
 'askSize': 3200,
 'marketCap': 274665324544,
 'fiftyTwoWeekLow': 57.47,
 'fiftyTwoWeekHigh': 73.53,
 'priceToSalesTrailing12Months': 5.923852,
 'fiftyDayAverage': 68.0868,
 'twoHundredDayAverage': 64.61825,
 'trailingAnnualDividendRate': 1.915,
 'trailingAnnualDividendYield': 0.030401649,
 'currency': 'USD',
 'enterpriseValue': 305255153664,
 'profitMargins': 0.2245,
 'floatShares': 3874561980,
 'sharesOutstanding': 4307800064,
 'sharesShort': 30816595,
 'sharesShortPriorMonth': 33950953,
 'sharesShortPreviousMonthDate': 1727654400,
 'dateShortInterest': 1730332800,
 'sharesPercentSharesOut': 0.0072000003,
 'heldPercentInsiders': 0.0995,
 'heldPercentInstitutions': 0.64628,
 'shortRatio': 2.36,
 'shortPercentOfFloat': 0.0072000003,
 'impliedSharesOutstanding': 4307800064,
 'bookValue': 6.153,
 'priceToBook': 10.362425,
 'lastFiscalYearEnd': 1703980800,
 'nextFiscalYearEnd': 1735603200,
 'mostRecentQuarter': 1727395200,
 'earningsQuarterlyGrowth': -0.077,
 'netIncomeToCommon': 10408999936,
 'trailingEps': 2.41,
 'forwardEps': 2.97,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1344816000,
 'enterpriseToRevenue': 6.584,
 'enterpriseToEbitda': 20.582,
 '52WeekChange': 0.0754652,
 'SandP52WeekChange': 0.2977997,
 'lastDividendValue': 0.485,
 'lastDividendDate': 1726185600,
 'exchange': 'NYQ',
 'quoteType': 'EQUITY',
 'symbol': 'KO',
 'underlyingSymbol': 'KO',
 'shortName': 'Coca-Cola Company (The)',
 'longName': 'The Coca-Cola Company',
 'firstTradeDateEpochUtc': -252322200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': '5fed318f-9c85-3ad1-b311-20392472c25a',
 'messageBoardId': 'finmb_26642',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 63.76,
 'targetHighPrice': 85.0,
 'targetLowPrice': 64.0,
 'targetMeanPrice': 74.38458,
 'targetMedianPrice': 75.5,
 'recommendationKey': 'none',
 'numberOfAnalystOpinions': 24,
 'totalCash': 18164000768,
 'totalCashPerShare': 4.217,
 'ebitda': 14830999552,
 'totalDebt': 47118000128,
 'quickRatio': 0.784,
 'currentRatio': 1.06,
 'totalRevenue': 46365999104,
 'debtToEquity': 167.358,
 'revenuePerShare': 10.753,
 'returnOnAssets': 0.08438,
 'returnOnEquity': 0.3723,
 'freeCashflow': 14018875392,
 'operatingCashflow': 5523999744,
 'earningsGrowth': -0.07,
 'revenueGrowth': -0.008,
 'grossMargins': 0.60433996,
 'ebitdaMargins': 0.31987,
 'operatingMargins': 0.30235,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.6885}

In [4]:
hist = stock.history()

In [5]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-10-22 00:00:00-04:00,69.000000,69.750000,68.680000,69.449997,18603300,0.0,0.0
2024-10-23 00:00:00-04:00,66.989998,68.699997,66.580002,68.010002,24655200,0.0,0.0
2024-10-24 00:00:00-04:00,67.650002,68.040001,66.949997,67.300003,17568800,0.0,0.0
2024-10-25 00:00:00-04:00,67.070000,67.699997,66.790001,66.919998,11138100,0.0,0.0
2024-10-28 00:00:00-04:00,66.959999,67.400002,66.599998,66.669998,10761400,0.0,0.0
2024-10-29 00:00:00-04:00,66.290001,66.339996,65.519997,65.559998,16525900,0.0,0.0
2024-10-30 00:00:00-04:00,65.510002,66.540001,65.320000,65.919998,14177800,0.0,0.0
2024-10-31 00:00:00-04:00,65.809998,65.989998,65.260002,65.309998,13383700,0.0,0.0
2024-11-01 00:00:00-04:00,65.470001,65.660004,64.889999,65.010002,12163100,0.0,0.0
2024-11-04 00:00:00-05:00,65.080002,65.419998,64.650002,65.110001,10984500,0.0,0.0
2024-11-05 00:00:00-05:00,64.639999,65.470001,64.639999,65.370003,8780200,0.0,0.0
2024-11-06 00:00:00-05:00,64.419998,64.860001,63.180000,63.700001,22899300,0.0,0.0
2024-11-07 00:00:00-05:00,64.290001,64.389999,63.599998,63.660000,14856100,0.0,0.0
2024-11-08 00:00:00-05:00,63.910000,64.239998,63.740002,63.919998,14719300,0.0,0.0
2024-11-11 00:00:00-05:00,63.990002,64.120003,63.250000,63.360001,13980900,0.0,0.0
2024-11-12 00:00:00-05:00,63.680000,63.750000,63.119999,63.200001,15021000,0.0,0.0
2024-11-13 00:00:00-05:00,63.049999,63.259998,62.490002,63.000000,13177600,0.0,0.0
2024-11-14 00:00:00-05:00,63.110001,63.110001,62.430000,62.549999,15910800,0.0,0.0
2024-11-15 00:00:00-05:00,62.490002,62.630001,61.389999,61.740002,26284300,0.0,0.0
2024-11-18 00:00:00-05:00,61.849998,62.139999,61.560001,61.860001,16079400,0.0,0.0
2024-11-19 00:00:00-05:00,61.900002,62.619999,61.630001,62.590000,16254800,0.0,0.0
2024-11-20 00:00:00-05:00,62.700001,63.009998,62.020000,62.990002,18904900,0.0,0.0
2024-11-21 00:00:00-05:00,63.150002,63.810001,62.950001,63.759998,17279400,0.0,0.0

In [6]:
hist = stock.history(
    start=start_date,
    interval=interval
)

In [7]:
str(hist.index.min().date())

'1980-01-01'

In [8]:
str(hist.index.max().date())

'2024-11-19'

In [9]:
hist.index = hist.index.strftime('%Y-%m-%d %H:%M:%S')
hist.index = pd.to_datetime(hist.index).tz_localize('UTC')

In [10]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-01-01 00:00:00+00:00,0.200930,0.204570,0.195106,0.203114,13502400,0.0,0.0
1980-01-08 00:00:00+00:00,0.203114,0.209666,0.203114,0.206025,42643200,0.0,0.0
1980-01-15 00:00:00+00:00,0.206026,0.206026,0.190738,0.195106,32985600,0.0,0.0
1980-01-22 00:00:00+00:00,0.195106,0.201658,0.190010,0.198746,48364800,0.0,0.0
1980-01-29 00:00:00+00:00,0.199474,0.208938,0.199474,0.201657,46545600,0.0,0.0
...,...,...,...,...,...,...,...
2024-10-22 00:00:00+00:00,69.000000,69.750000,66.580002,66.669998,82726800,0.0,0.0
2024-10-29 00:00:00+00:00,66.290001,66.540001,64.650002,65.110001,67235000,0.0,0.0
2024-11-05 00:00:00+00:00,64.639999,65.470001,63.180000,63.360001,75235800,0.0,0.0
2024-11-12 00:00:00+00:00,63.680000,63.750000,61.389999,61.860001,86473100,0.0,0.0
2024-11-19 00:00:00+00:00,61.900002,63.810001,61.630001,63.759998,69512442,0.0,0.0

In [11]:
symbol =  mapping_symbol.get(symbol, symbol)

In [12]:
symbol = symbol.replace(".", "_").lower()

In [13]:
file_name = f"../../data/{symbol}/{symbol}-{str(hist.index.min().date())}-to-{str(hist.index.max().date())}_{interval}.csv"

In [14]:
file_name = file_name.replace("-", "_")

In [15]:
file_name

'../../data/coca_cola/coca_cola_1980_01_01_to_2024_11_19_1wk.csv'

In [16]:

hist.to_csv(file_name)