In [6]:
import yfinance as yf
from datetime import  datetime

In [4]:
btc = yf.Ticker('BTC-USD')

In [5]:
btc.info

{'name': 'Bitcoin',
 'startDate': 1278979200,
 'description': 'Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,776,646. The last known price of Bitcoin is 69,579.71706891 USD and is up 0.13 over the last 24 hours. It is currently trading on 11793 active market(s) with $41,625,641,410.52 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 69346.72,
 'open': 69346.72,
 'dayLow': 68151.54,
 'dayHigh': 69346.72,
 'regularMarketPreviousClose': 69346.72,
 'regularMarketOpen': 69346.72,
 'regularMarketDayLow': 68151.54,
 'regularMarketDayHigh': 69346.72,
 'volume': 19885869056,
 'regularMarketVolume': 19885869056,
 'averageVolume': 31668401695,
 'averageVolume10days': 37006387567,
 'averageDailyVolume10Day': 37006387567,
 'marketCap': 1347828842496,
 'fiftyTwoWeekLow': 34545.816,
 'fiftyTwoWeekHigh': 73750.07,
 'fiftyDayAverage': 64641.273,
 'twoHundredDayAverage': 63385.03,
 'currency': 'USD',
 'fromCurrency': 'BTC',
 'toCurrency': 'USD=X',
 'lastMarket': 'CoinMarketCap',
 'coinMarketCapLink': 'https://coinmarketcap.com/currencies/bitcoin',
 'volume24Hr': 19885869056,
 'volumeAllCurrencies': 19885869056,
 'circulatingSupply': 19776940,
 'exchange': 'CCC',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'BTC-USD',
 'underlyingSymbol': 'BTC-USD',
 'shortName': 'Bitcoin USD',
 'longName': 'Bitcoin USD',
 'firstTradeDateEpochUtc': 1410912000,
 'timeZoneFullName': 'UTC',
 'timeZoneShortName': 'UTC',
 'uuid': '74397779-1589-3270-8c45-b7f1a7345b3a',
 'messageBoardId': 'finmb_BTC_CCC',
 'trailingPegRatio': None}

In [7]:
datetime.fromtimestamp(1410912000)

datetime.datetime(2014, 9, 17, 7, 0)

In [8]:
hist = btc.history()

In [10]:
hist.index.min()

Timestamp('2024-10-03 00:00:00+0000', tz='UTC')

In [11]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-10-03 00:00:00+00:00,60632.484375,61469.039062,59878.804688,60759.402344,36106447279,0.0,0.0
2024-10-04 00:00:00+00:00,60754.625000,62465.992188,60459.941406,62067.476562,29585472513,0.0,0.0
2024-10-05 00:00:00+00:00,62067.609375,62371.023438,61689.582031,62089.949219,13305410749,0.0,0.0
2024-10-06 00:00:00+00:00,62084.988281,62959.570312,61833.148438,62818.953125,14776233667,0.0,0.0
2024-10-07 00:00:00+00:00,62819.109375,64443.707031,62152.550781,62236.660156,34253562610,0.0,0.0
2024-10-08 00:00:00+00:00,62221.644531,63174.304688,61843.562500,62131.968750,28134475157,0.0,0.0
2024-10-09 00:00:00+00:00,62131.726562,62508.835938,60314.613281,60582.101562,27670982363,0.0,0.0
2024-10-10 00:00:00+00:00,60581.929688,61236.722656,58895.207031,60274.500000,30452813570,0.0,0.0
2024-10-11 00:00:00+00:00,60275.460938,63400.871094,60046.125000,62445.089844,30327141594,0.0,0.0
2024-10-12 00:00:00+00:00,62444.617188,63448.785156,62443.269531,63193.023438,16744110886,0.0,0.0
2024-10-13 00:00:00+00:00,63192.945312,63272.652344,62035.636719,62851.375000,18177529690,0.0,0.0
2024-10-14 00:00:00+00:00,62848.398438,66482.492188,62442.152344,66046.125000,43706958056,0.0,0.0
2024-10-15 00:00:00+00:00,66050.367188,67881.679688,64809.195312,67041.109375,48863870879,0.0,0.0
2024-10-16 00:00:00+00:00,67042.460938,68375.289062,66758.726562,67612.718750,38195189534,0.0,0.0
2024-10-17 00:00:00+00:00,67617.078125,67912.210938,66647.390625,67399.835938,32790898511,0.0,0.0
2024-10-18 00:00:00+00:00,67419.109375,68969.750000,67177.820312,68418.789062,36857165014,0.0,0.0
2024-10-19 00:00:00+00:00,68418.976562,68668.007812,68024.640625,68362.734375,14443497908,0.0,0.0
2024-10-20 00:00:00+00:00,68364.179688,69359.007812,68105.718750,69001.703125,18975847518,0.0,0.0
2024-10-21 00:00:00+00:00,69002.000000,69462.734375,66829.851562,67367.851562,37498611780,0.0,0.0
2024-10-22 00:00:00+00:00,67360.703125,67801.578125,66581.367188,67361.406250,31808472566,0.0,0.0
2024-10-23 00:00:00+00:00,67362.375000,67402.742188,65188.035156,66432.195312,32263980353,0.0,0.0
2024-10-24 00:00:00+00:00,66653.703125,68798.960938,66454.101562,68161.054688,31414428647,0.0,0.0
2024-10-25 00:00:00+00:00,68165.296875,68722.156250,65521.792969,66642.414062,41469984306,0.0,0.0
2024-10-26 00:00:00+00:00,66628.734375,67317.921875,66360.593750,67014.695312,19588098156,0.0,0.0
2024-10-27 00:00:00+00:00,67023.476562,68221.312500,66847.226562,67929.296875,16721307878,0.0,0.0
2024-10-28 00:00:00+00:00,67922.671875,70212.265625,67535.132812,69907.757812,38799856657,0.0,0.0
2024-10-29 00:00:00+00:00,69910.046875,73577.210938,69729.914062,72720.492188,58541874402,0.0,0.0
2024-10-30 00:00:00+00:00,72715.367188,72905.296875,71411.734375,72339.539062,40646637831,0.0,0.0
2024-10-31 00:00:00+00:00,72335.046875,72662.312500,69590.500000,70215.187500,40627912076,0.0,0.0
2024-11-01 00:00:00+00:00,70216.898438,71559.015625,68779.703125,69482.468750,49989795365,0.0,0.0
2024-11-03 00:00:00+00:00,69346.718750,69346.718750,68261.546875,68261.546875,20025257984,0.0,0.0

In [12]:
hist = btc.history(
    start="2014-09-17"
)

In [16]:
hist.index.max()

Timestamp('2024-11-03 00:00:00+0000', tz='UTC')

In [15]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,0.0,0.0
2014-09-18 00:00:00+00:00,456.859985,456.859985,413.104004,424.440002,34483200,0.0,0.0
2014-09-19 00:00:00+00:00,424.102997,427.834991,384.532013,394.795990,37919700,0.0,0.0
2014-09-20 00:00:00+00:00,394.673004,423.295990,389.882996,408.903992,36863600,0.0,0.0
2014-09-21 00:00:00+00:00,408.084991,412.425995,393.181000,398.821014,26580100,0.0,0.0
...,...,...,...,...,...,...,...
2024-10-29 00:00:00+00:00,69910.046875,73577.210938,69729.914062,72720.492188,58541874402,0.0,0.0
2024-10-30 00:00:00+00:00,72715.367188,72905.296875,71411.734375,72339.539062,40646637831,0.0,0.0
2024-10-31 00:00:00+00:00,72335.046875,72662.312500,69590.500000,70215.187500,40627912076,0.0,0.0
2024-11-01 00:00:00+00:00,70216.898438,71559.015625,68779.703125,69482.468750,49989795365,0.0,0.0
2024-11-03 00:00:00+00:00,69346.718750,69346.718750,68123.492188,68123.492188,20160018432,0.0,0.0

In [17]:
hist.to_csv('btc-2024-09-17-to-2024-11-03')