In [1]:
import yfinance as yf
from datetime import  datetime

In [2]:
symbol = "0P0000HY8X.VN"
stock = yf.Ticker(symbol)

In [3]:
stock.info

{'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1264.48,
 'regularMarketPreviousClose': 1264.48,
 'fiftyTwoWeekLow': 1088.06,
 'fiftyTwoWeekHigh': 1301.51,
 'fiftyDayAverage': 1270.1718,
 'twoHundredDayAverage': 1246.4135,
 'currency': 'VND',
 'exchange': 'VSE',
 'quoteType': 'INDEX',
 'symbol': '0P0000HY8X.VN',
 'underlyingSymbol': '0P0000HY8X.VN',
 'shortName': 'Vietnam VN Index",',
 'longName': 'Vietnam VN Index',
 'firstTradeDateEpochUtc': 1581472800,
 'timeZoneFullName': 'Asia/Bangkok',
 'timeZoneShortName': 'ICT',
 'uuid': 'd7ccdc45-da20-3fb7-a255-ed9e89a9bacf',
 'gmtOffSetMilliseconds': 25200000,
 'trailingPegRatio': None}

In [4]:
datetime.fromtimestamp(1410912000)

datetime.datetime(2014, 9, 17, 7, 0)

In [5]:
hist = stock.history()

In [6]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-10-14 00:00:00+07:00,1286.339966,1286.339966,1286.339966,1286.339966,0,0.0,0.0
2024-10-15 00:00:00+07:00,1281.079956,1281.079956,1281.079956,1281.079956,0,0.0,0.0
2024-10-16 00:00:00+07:00,1279.479980,1279.479980,1279.479980,1279.479980,0,0.0,0.0
2024-10-17 00:00:00+07:00,1286.520020,1286.520020,1286.520020,1286.520020,0,0.0,0.0
2024-10-18 00:00:00+07:00,1285.459961,1285.459961,1285.459961,1285.459961,0,0.0,0.0
2024-10-21 00:00:00+07:00,1279.770020,1279.770020,1279.770020,1279.770020,0,0.0,0.0
2024-10-22 00:00:00+07:00,1269.890015,1269.890015,1269.890015,1269.890015,0,0.0,0.0
2024-10-23 00:00:00+07:00,1270.900024,1270.900024,1270.900024,1270.900024,0,0.0,0.0
2024-10-24 00:00:00+07:00,1257.410034,1257.410034,1257.410034,1257.410034,0,0.0,0.0
2024-10-25 00:00:00+07:00,1252.719971,1252.719971,1252.719971,1252.719971,0,0.0,0.0
2024-10-28 00:00:00+07:00,1254.770020,1254.770020,1254.770020,1254.770020,0,0.0,0.0
2024-10-29 00:00:00+07:00,1261.780029,1261.780029,1261.780029,1261.780029,0,0.0,0.0
2024-10-30 00:00:00+07:00,1258.630005,1258.630005,1258.630005,1258.630005,0,0.0,0.0
2024-10-31 00:00:00+07:00,1264.479980,1264.479980,1264.479980,1264.479980,0,0.0,0.0
2024-11-01 00:00:00+07:00,1254.890015,1254.890015,1254.890015,1254.890015,0,0.0,0.0
2024-11-04 00:00:00+07:00,1244.709961,1244.709961,1244.709961,1244.709961,0,0.0,0.0
2024-11-05 00:00:00+07:00,1245.760010,1245.760010,1245.760010,1245.760010,0,0.0,0.0
2024-11-06 00:00:00+07:00,1261.280029,1261.280029,1261.280029,1261.280029,0,0.0,0.0
2024-11-07 00:00:00+07:00,1259.750000,1259.750000,1259.750000,1259.750000,0,0.0,0.0
2024-11-08 00:00:00+07:00,1252.560059,1252.560059,1252.560059,1252.560059,0,0.0,0.0
2024-11-11 00:00:00+07:00,1250.319946,1250.319946,1250.319946,1250.319946,0,0.0,0.0

In [7]:
hist = stock.history(
    start="2017-01-01"
)

In [8]:
str(hist.index.min().date())

'2020-02-12'

In [9]:
str(hist.index.max().date())

'2024-11-11'

In [10]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-02-12 00:00:00+07:00,937.679993,937.679993,937.679993,937.679993,0,0.0,0.0
2020-02-13 00:00:00+07:00,938.239990,938.239990,938.239990,938.239990,0,0.0,0.0
2020-02-14 00:00:00+07:00,937.450012,937.450012,937.450012,937.450012,0,0.0,0.0
2020-02-18 00:00:00+07:00,927.929993,927.929993,927.929993,927.929993,0,0.0,0.0
2020-02-19 00:00:00+07:00,928.760010,928.760010,928.760010,928.760010,0,0.0,0.0
...,...,...,...,...,...,...,...
2024-11-05 00:00:00+07:00,1245.760010,1245.760010,1245.760010,1245.760010,0,0.0,0.0
2024-11-06 00:00:00+07:00,1261.280029,1261.280029,1261.280029,1261.280029,0,0.0,0.0
2024-11-07 00:00:00+07:00,1259.750000,1259.750000,1259.750000,1259.750000,0,0.0,0.0
2024-11-08 00:00:00+07:00,1252.560059,1252.560059,1252.560059,1252.560059,0,0.0,0.0
2024-11-11 00:00:00+07:00,1250.319946,1250.319946,1250.319946,1250.319946,0,0.0,0.0

In [11]:
if symbol == "0P0000HY8X.VN":
    symbol = "VNINDEX"

In [12]:
symbol = symbol.replace(".", "_").lower()

In [13]:
file_name = f"./data/{symbol}-{str(hist.index.min().date())}-to-{str(hist.index.max().date())}.csv"

In [14]:
file_name = file_name.replace("-", "_")

In [15]:
file_name

'./data/vnindex_2020_02_12_to_2024_11_11.csv'

In [16]:

hist.to_csv(file_name)